<<<<<<< HEAD
# Generated by Django 4.1.6 on 2023-04-16 10:02
=======
# Generated by Django 4.1.7 on 2023-02-19 14:39
>>>>>>> 1860828192de2b003f031cabe0dad3d55f782c34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('content', models.TextField(blank=True)),
                ('author', models.TextField(blank=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
=======
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('content', models.TextField(blank=True)),
                ('author', models.TextField(blank=True)),
                ('price', models.IntegerField()),
>>>>>>> 1860828192de2b003f031cabe0dad3d55f782c34
            ],
        ),
    ]
